### ISSUE TITLE
wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by feliksg** [attr-encrypted/attr_encrypted#270] opened 2017-07-03 05:42 UTC
I'm using rails 5.1.2 with attr_encrypted 3.0.3 and I have a few fields in my devise user model that I specified to be encrypted, but when I try to create a user from the console with `User.create(...)`, I get the wrong number of arguments error.

I have my encrypted attributes defined like this (my real keys are redacted but were generated using `SecureRandom.base64(32)`:

```
attr_encrypted :first_name,     key: 'This is a key that is 256 bits!!'
attr_encrypted :last_name,      key: 'This is a key that is 256 bits!!'
```

I saw in an old issue that protected_attributes was the cause, but I don't have it in my gemfile (see my gemfile here: https://gist.github.com/feliksg/3e29d792d0f79b850a6468833bf5913d).

Any ideas on how to fix this?

**Comment by jonpearse** [comment] 2017-07-18 11:07
I’ve just stumbled across this having come across the same issue in my project, and thought I’d post what I’ve found.

The issue is because the `two_factor_authentication` gem overwrites attr_encrypted’s `encrypt` and `decrypt` functions with its own incompatible functions which work fine for it, but not so much for anything else.

Someone’s already opened a [PR for two_factor_authentication](https://github.com/Houdini/two_factor_authentication/pull/126) which fixes the issue, and hopefully should be accepted into the `two_factor_authentication` gem shortly ( 🤞 ).
As a temporary workaround, you can use @leanucci’s workaround directly by replacing line 25 of your gemfile with the following:

`gem 'two_factor_authentication', github: 'leanucci/two_factor_authentication', branch: 'encryption_methods_unique_names'`

Obviously, it’d be worth keeping an eye on the `two_factor_authentication` gem so you can revert back as soon as they’ve patched the issue.

Hope this is helpful!

**Comment by Houdini** [comment] 2017-07-18 19:30
fixed in gem two_factor_authentication, version 2.0.1

**Comment by feliksg** [comment] 2017-07-18 22:09
thanks so much @jonpearse!

**Closed** 2017-07-18 22:12 UTC
